### ISSUE TITLE
OpenTofu support

### ISSUE THREAD

**Issue by AlexW00** [RoseSecurity/Kuzco#8]
**Is your feature request related to a problem? Please describe.**
I don't have terraform installed. Instead I use [OpenTofu](https://opentofu.org/). However, when running Kuzco without terraform installed, the following error occurs:
```
Error: error extracting provider schema: error running terraform init: exec: "terraform": executable file not found in $PATH
```

**Describe the solution you'd like**
Kuzco works fine with just OpenTofu installed

**Describe alternatives you've considered**
- `alias terraform=tofu` does not work

**Comment by RoseSecurity** [comment]
Thank you for this issue! I'm adding it to the roadmap and will add support this week for this request

**Comment by RoseSecurity** [comment]
[OpenTofu configurations](https://github.com/RoseSecurity/Kuzco/releases/tag/v0.6.0) are now supported! Enjoy!
